default_env: &default
  adapter: postgresql
  encoding: unicode
  # database: s_original
  database: s_english

development:
  <<: *default

production:
  <<: *default
  host: dpg-ck0r1e1jbtgs73cnkaj0-a
  database: s_original_rdrq
  username: s_original_rdrq_user
  password: nXDmTCDESjCdhKDUOYyMCXtDdqG4Fsmz